"""Baseline schema for Endurance Mission Control.

This revision creates the current schema directly from SQLAlchemy metadata so we
can safely adopt Alembic before introducing incremental autogenerated changes.
"""

from __future__ import annotations

from alembic import op

from app.database import Base
from app import models  # noqa: F401


revision = "20260522_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
